### ISSUE TITLE
HomeWork 3 

### ISSUE THREAD

**Issue by aborundiya** [ConsenSys/india-training#38]
In the Readme file,  ****"In the second part, due to other week, you should develop a web interface to interact with the contract."****
Is the second part due next week ? 

Amit

**Comment by anurag-git** [comment]
Yes, want to confirm the following:
1st part related to Smart Contract is due by Thursday, this week. Right?
and
2nd part related to User Interface is due by Thursday, next week. Right?

Anurag Dashputre

**Comment by danielnovy** [comment]
Yes, I confirm that info!

The solidity contract should be deployed to the Gyaan Network by Thursday. I will update the README to include this information.

The web interface should be delivered by Thursday next week. It should be deployed in a public internet address where I will be able to play around with it.

**Comment by anishcr** [comment]
1) Anyone can contribute ethers to the contract at any time.

2) This means the amount held in the contract can vary from time to time.

3) When someone submits a proprosal, he can submit value which is 10% of the value held by that contract at that time.

4) A proposal will be in Submitted state, Approved state, Rejected State, Complete Money Withdrawn
 state or partial money withdrawn state.

  Can the beneficiary withdraw amounts (for the same proposal) at different times? (only requirement is that the sum of withdrawal has to be less than or equal to the approved amount.

5) A beneficiary can submit only one proposal at a time.
  He can propose only after his previous proposals are in one of the following states - Rejected o
r Complete Money Withdrawn state?

6)Can an approver keep changing his mind by calling Approve or Reject for a given beneficiary as many times as possible (if the proposal is in Submitted state)?

7) Since a beneficiary can withdraw at any time, there is a possibility that the contract does not
 have enough ether to transfer.

  For eg, 20 proposals were submitted each for 10% of the contract value.   If all are approved, then there is not enough ethers to provide for all. Whoever withdraws first will receive the ether!!!
